export default [
  {
    title: "Ansormed",
    github: "https://github.com/donnarch/Ansormeed",
    vercel: "https://ansormeed-k5t2.vercel.app/",
  },
  {
    title: "Akademnashr",
    github: "https://github.com/donnarch/akademnashr",
    vercel: "https://akademnashr-bice.vercel.app/",
  },
  {
    title: "Coffee street",
    github: "https://github.com/donnarch/caffee",
    vercel: "https://3-mu-lake.vercel.app/",
  },
  {
    title: "Bem h/m 3",
    github: "https://github.com/donnarch/bem-homework-2",
    vercel: "https://bem-homework-2.vercel.app/",
  },
  {
    title: "Bem h/m4",
    github: "https://github.com/donnarch/bem-homework-4",
    vercel: "https://bem-homework-4.vercel.app/",
  },
  {
    title: "Bem h/m",
    github: "https://github.com/donnarch/bem-pack",
    vercel: "https://bem-pack.vercel.app/",
  },
  {
    title: "Bem h/m3",
    github: "https://github.com/donnarch/bem-homework-3",
    vercel: "https://bem-homework-3.vercel.app/",
  },
  {
    title: "Recipe page",
    github: "https://github.com/donnarch/recipe-page",
    vercel: "https://recipe-page-omeelete.vercel.app/",
  },
  {
    title: "",
    github: "",
    vercel: "",
  },
];
